import { Component, OnInit } from '@angular/core';
import { ActivatedRoute } from '@angular/router';

@Component({
  selector: 'app-sbn-article-detail',
  templateUrl: './sbn-article-detail.component.html',
  styleUrls: ['./sbn-article-detail.component.scss'],
})
export class SbnArticleDetailComponent implements OnInit {
  article: any;

  // Base de datos extendida con el contenido largo
  articlesData: any = {
    1: {
      category: 'Agua y gestión hídrica',
      title:
        'Captación de agua de lluvia como estrategia comunitaria para la resiliencia hídrica',
      heroImg: 'assets/repo/agua1-full.jpg',
      intro: `El acceso al agua potable es uno de los principales desafíos que enfrentan muchas comunidades vulnerables, especialmente en territorios afectados por el cambio climático, la urbanización acelerada o la falta de infraestructura básica. En este contexto, las soluciones basadas en la naturaleza (SbN) ofrecen alternativas sostenibles que permiten gestionar el recurso hídrico de manera local, eficiente y resiliente.`,
      content1: `La captación de agua de lluvia se presenta como una estrategia accesible que combina conocimientos técnicos sencillos con prácticas tradicionales, fortaleciendo la autonomía comunitaria y reduciendo la presión sobre fuentes convencionales de agua.`,
      subhead1: '¿En qué consiste la captación de agua de lluvia?',
      body1: `La captación de agua de lluvia es un sistema que recolecta, conduce y almacena el agua proveniente de precipitaciones para su uso posterior. Generalmente se compone de superficies de captación (cubiertas o techos), canaletas, filtros y tanques de almacenamiento.`,
      body2: `Desde la perspectiva de las SbN, esta práctica aprovecha un proceso natural —la precipitación— sin alterarlo, integrándolo de forma armónica en el entorno construido y territorial.`,
      subhead2: 'Beneficios sociales y ambientales',
      body3: `Para las comunidades, estos sistemas pueden representar una fuente complementaria de agua para usos domésticos, riego de huertos comunitarios o limpieza de espacios públicos. Esto reduce la dependencia de redes formales, muchas veces inexistentes o inestables en contextos vulnerables.`,
      body4: `Desde el punto de vista ambiental, la captación de lluvia disminuye la escorrentía superficial, contribuyendo a la reducción de inundaciones y la erosión del suelo.`,
      immersiveImg: 'assets/repo/esquema-lluvia.jpg',
      subhead3: 'Oportunidades para la colaboración',
      body5: `Las comunidades aportan el conocimiento del territorio, las necesidades reales y las prácticas culturales existentes, mientras que los profesionales pueden contribuir con criterios técnicos, mejoras en el diseño, selección de materiales y estrategias de mantenimiento.`,
      conclusion: `Cuando estos elementos se integran desde el inicio, la captación de lluvia se convierte en una solución de bajo costo, alto impacto y gran valor educativo.`,
    },
    2: {
      category: 'Agua y gestión hídrica',
      title:
        'Restauración de riberas para la reducción del riesgo de inundaciones',
      heroImg: 'assets/repo/agua2-full.jpg',
      intro: `Las inundaciones constituyen uno de los riesgos naturales más frecuentes y destructivos en territorios urbanos y rurales. La ocupación de zonas inundables y la pérdida de vegetación han incrementado la vulnerabilidad.`,
      content1: `La restauración de riberas se consolida como una SbN que permite reducir el riesgo de inundaciones, trabajar con los procesos naturales del río, no contra ellos.`,
      subhead1: '¿Qué es la restauración de riberas?',
      body1: `Consiste en recuperar las funciones ecológicas y geomorfológicas de los márgenes de ríos y quebradas. Esto incluye acciones como la revegetación con especies nativas y la estabilización natural de taludes.`,
      subhead2: 'Beneficios para la reducción del riesgo',
      body3: `Uno de los principales aportes es la disminución de la velocidad y la energía del agua durante lluvias intensas. Las raíces de la vegetación estabilizan el suelo, reduciendo los deslizamientos.`,
      immersiveImg: 'assets/repo/ribera-antes-despues.jpg',
      subhead3: 'Colaboración entre comunidad y profesionales',
      body5: `Las comunidades conocen el comportamiento histórico del río. Los profesionales voluntarios pueden aportar conocimientos en hidrología, ecología y arquitectura del paisaje.`,
      conclusion: `La restauración de riberas se convierte en una estrategia de bajo impacto, alta efectividad y gran valor educativo.`,
    },
    3: {
      category: 'Agua y gestión hídrica',
      title:
        'Infraestructura verde para la gestión sostenible de aguas urbanas',
      heroImg: 'assets/repo/agua3-full.jpg',
      intro: `Las ciudades enfrentan crecientes desafíos relacionados con la gestión del agua: inundaciones urbanas, sobrecarga de sistemas de drenaje, contaminación de cuerpos hídricos y escasez de espacios verdes. Estos problemas se intensifican en barrios vulnerables, donde la infraestructura convencional suele ser insuficiente o inexistente.`,
      content1: `La infraestructura verde surge como una solución basada en la naturaleza que integra vegetación, suelo y agua para gestionar las aguas pluviales de manera más eficiente, resiliente y sostenible. En lugar de evacuar rápidamente el agua, estas soluciones buscan retenerla, infiltrarla y aprovecharla localmente.`,
      subhead1: '¿Qué se entiende por infraestructura verde?',
      body1: `La infraestructura verde comprende un conjunto de soluciones como jardines de lluvia, zanjas de infiltración, pavimentos permeables, techos verdes y áreas verdes multifuncionales.`,
      body2: `Estas intervenciones imitan procesos naturales del ciclo hidrológico, permitiendo que el agua de lluvia se infiltre en el suelo o sea reutilizada, complementando y aliviando la infraestructura gris tradicional.`,
      subhead2: 'Beneficios en la gestión del agua urbana',
      body3: `Uno de los principales beneficios es la reducción del volumen y la velocidad del escurrimiento superficial durante lluvias intensas. Los jardines de lluvia y superficies permeables capturan el agua, disminuyendo la probabilidad de inundaciones locales.`,
      body4: `Además, estos sistemas contribuyen a la recarga de acuíferos y a la mejora de la calidad del agua, ya que el suelo y la vegetación actúan como filtros naturales que retienen contaminantes.`,
      immersiveImg: 'assets/repo/infraestructura-verde-esquema.jpg',
      subhead3: 'Impactos sociales y ambientales',
      body5: `La infraestructura verde mejora el confort térmico, reduce las islas de calor y aporta espacios verdes de uso cotidiano, impactando directamente en la salud, el bienestar y la calidad de vida de las comunidades urbanas.`,
      conclusion: `Cuando se integran de forma gradual y participativa, estas soluciones se convierten en herramientas poderosas de adaptación climática urbana, especialmente relevantes en contextos de alta vulnerabilidad.`,
    },
    4: {
      category: 'Biodiversidad y restauración ecológica',
      title:
        'Corredores ecológicos comunitarios para la recuperación de la biodiversidad local',
      heroImg: 'assets/repo/bio1-full.jpg',
      intro: `La fragmentación del territorio es una de las principales causas de la pérdida de biodiversidad, especialmente en áreas urbanas y periurbanas donde los ecosistemas naturales han sido reemplazados por infraestructura y usos intensivos del suelo.`,
      content1: `En este contexto, los corredores ecológicos comunitarios se presentan como una solución basada en la naturaleza que permite reconectar hábitats aislados, facilitando el movimiento de especies y la recuperación de procesos ecológicos.`,
      subhead1: '¿Qué son los corredores ecológicos?',
      body1: `Los corredores ecológicos son franjas de vegetación que conectan áreas naturales fragmentadas, como parques, riberas, reservas o espacios verdes urbanos.`,
      body2: `A escala comunitaria, pueden materializarse mediante calles arboladas, huertos comunitarios, bordes verdes, jardines y espacios públicos naturalizados.`,
      subhead2: 'Beneficios ecológicos y territoriales',
      body3: `Estos corredores favorecen la movilidad de fauna, la dispersión de semillas y el mantenimiento de la biodiversidad local.`,
      body4: `Además, contribuyen a mejorar la calidad del aire, regular la temperatura y fortalecer la resiliencia del territorio frente al cambio climático.`,
      immersiveImg: 'assets/repo/corredor-ecologico-esquema.jpg',
      subhead3: 'Participación comunitaria y colaboración técnica',
      body5: `Las comunidades desempeñan un rol clave en la identificación de espacios estratégicos y en el cuidado cotidiano de los corredores, mientras que los profesionales voluntarios pueden apoyar en el diseño, selección de especies nativas y planificación ecológica.`,
      conclusion: `Los corredores ecológicos comunitarios no solo restauran la biodiversidad, sino que también fortalecen el vínculo entre las personas y su entorno natural.`,
    },
    5: {
      category: 'Biodiversidad y restauración ecológica',
      title: 'Restauración participativa de suelos degradados',
      heroImg: 'assets/repo/bio2-full.jpg',
      intro: `La degradación del suelo es un problema crítico en muchos territorios rurales y periurbanos, producto de prácticas extractivas, deforestación, sobrepastoreo y expansión urbana no planificada.`,
      content1: `La restauración participativa de suelos se plantea como una solución basada en la naturaleza que combina técnicas ecológicas con la participación activa de las comunidades para recuperar la fertilidad y funcionalidad del suelo.`,
      subhead1: '¿En qué consiste la restauración de suelos?',
      body1: `La restauración de suelos incluye prácticas como la incorporación de materia orgánica, el control de la erosión, la revegetación con especies nativas y el manejo adecuado del agua.`,
      body2: `Estas acciones buscan restablecer la estructura del suelo, su capacidad de retención hídrica y su biodiversidad microbiana.`,
      subhead2: 'Beneficios ambientales y productivos',
      body3: `Un suelo sano mejora la producción de alimentos, reduce la erosión y aumenta la resiliencia frente a sequías e inundaciones.`,
      body4: `Además, contribuye a la captura de carbono y a la recuperación de servicios ecosistémicos fundamentales para la vida.`,
      immersiveImg: 'assets/repo/restauracion-suelo-esquema.jpg',
      subhead3: 'Aprendizaje colectivo y acompañamiento técnico',
      body5: `La participación comunitaria permite adaptar las técnicas a cada territorio, mientras que los profesionales voluntarios pueden aportar conocimientos en agroecología, manejo de suelos y monitoreo ambiental.`,
      conclusion: `La restauración participativa de suelos fortalece la autonomía local y promueve un manejo más justo y sostenible del territorio.`,
    },
    6: {
      category: 'Biodiversidad y restauración ecológica',
      title:
        'Reforestación con especies nativas como estrategia de resiliencia territorial',
      heroImg: 'assets/repo/bio3-full.jpg',
      intro: `La pérdida de cobertura vegetal es una de las principales causas de la degradación ambiental, afectando la biodiversidad, el ciclo del agua y la estabilidad de los territorios.`,
      content1: `La reforestación con especies nativas se presenta como una solución basada en la naturaleza que contribuye a restaurar ecosistemas, fortalecer la resiliencia territorial y generar beneficios sociales.`,
      subhead1: 'Importancia de las especies nativas',
      body1: `Las especies nativas están adaptadas a las condiciones climáticas y ecológicas locales, lo que las hace más resistentes y funcionales dentro del ecosistema.`,
      body2: `Su uso favorece la recuperación de fauna local, el equilibrio ecológico y la sostenibilidad a largo plazo de los procesos de restauración.`,
      subhead2: 'Impactos ecológicos y sociales',
      body3: `La reforestación mejora la infiltración del agua, reduce la erosión del suelo y contribuye a la regulación del microclima.`,
      body4: `A nivel social, estos proyectos pueden generar empleo local, fortalecer la identidad territorial y promover la educación ambiental.`,
      immersiveImg: 'assets/repo/reforestacion-nativa-esquema.jpg',
      subhead3: 'Procesos colaborativos de reforestación',
      body5: `Las comunidades aportan conocimiento sobre el territorio y su historia ambiental, mientras que los profesionales voluntarios pueden apoyar en la planificación, selección de especies y seguimiento técnico.`,
      conclusion: `La reforestación con especies nativas es una estrategia clave para construir territorios más resilientes, saludables y socialmente cohesionados.`,
    },
    7: {
      category: 'Seguridad alimentaria',
      title: 'Huertos comunitarios como herramienta de soberanía alimentaria',
      heroImg: 'assets/repo/alimentacion1-full.jpg',
      intro: `La inseguridad alimentaria afecta a millones de personas, especialmente en comunidades urbanas y rurales vulnerables donde el acceso a alimentos frescos, nutritivos y asequibles es limitado.`,
      content1: `Los huertos comunitarios surgen como una solución basada en la naturaleza que permite producir alimentos a pequeña escala, fortalecer la cohesión social y promover prácticas sostenibles de uso del suelo.`,
      subhead1: '¿Qué son los huertos comunitarios?',
      body1: `Los huertos comunitarios son espacios colectivos destinados al cultivo de alimentos para el autoconsumo, el intercambio o la venta local, gestionados de forma participativa por la comunidad.`,
      body2: `Estos espacios pueden desarrollarse en terrenos baldíos, patios comunales, escuelas o centros barriales, adaptándose a distintos contextos territoriales.`,
      subhead2: 'Beneficios para la seguridad y soberanía alimentaria',
      body3: `La producción local de alimentos reduce la dependencia de cadenas de suministro externas y mejora el acceso a productos frescos y culturalmente adecuados.`,
      body4: `Además, los huertos comunitarios fomentan el aprendizaje intergeneracional, la educación nutricional y la recuperación de saberes agrícolas tradicionales.`,
      immersiveImg: 'assets/repo/huertos-comunitarios-esquema.jpg',
      subhead3: 'Colaboración comunitaria y apoyo técnico',
      body5: `Las comunidades lideran la gestión cotidiana del huerto, mientras que profesionales voluntarios pueden aportar conocimientos en diseño agrícola, riego eficiente, compostaje y manejo de suelos.`,
      conclusion: `Los huertos comunitarios no solo producen alimentos, sino que fortalecen la autonomía, la resiliencia y el tejido social de los territorios.`,
    },
    8: {
      category: 'Seguridad alimentaria',
      title: 'Agroecología aplicada a pequeños sistemas productivos locales',
      heroImg: 'assets/repo/alimentacion2-full.jpg',
      intro: `Los pequeños sistemas productivos locales enfrentan desafíos como la degradación del suelo, la dependencia de insumos externos y la vulnerabilidad frente al cambio climático.`,
      content1: `La agroecología propone un enfoque integral que combina conocimientos científicos y saberes locales para diseñar sistemas agrícolas más sostenibles, resilientes y socialmente justos.`,
      subhead1: 'Principios de la agroecología',
      body1: `La agroecología se basa en principios como la diversidad de cultivos, el reciclaje de nutrientes, la conservación del suelo y el fortalecimiento de las interacciones ecológicas.`,
      body2: `Estos principios permiten reducir el uso de agroquímicos, mejorar la fertilidad del suelo y aumentar la estabilidad de la producción.`,
      subhead2: 'Aplicación en contextos comunitarios',
      body3: `En comunidades rurales y periurbanas, la agroecología puede implementarse mediante policultivos, rotación de cultivos, abonos orgánicos y control biológico de plagas.`,
      body4: `Estas prácticas fortalecen la autosuficiencia productiva y reducen los costos de producción para las familias agricultoras.`,
      immersiveImg: 'assets/repo/agroecologia-esquema.jpg',
      subhead3: 'Aprendizaje colectivo y acompañamiento técnico',
      body5: `La implementación agroecológica se potencia cuando existe intercambio de experiencias entre productores y acompañamiento de profesionales voluntarios en procesos de capacitación y monitoreo.`,
      conclusion: `La agroecología aplicada a pequeña escala es una estrategia clave para mejorar la seguridad alimentaria y la sostenibilidad de los sistemas productivos locales.`,
    },
    9: {
      category: 'Seguridad alimentaria',
      title:
        'Sistemas agroforestales para la diversificación productiva sostenible',
      heroImg: 'assets/repo/alimentacion3-full.jpg',
      intro: `La simplificación de los sistemas agrícolas ha generado pérdida de biodiversidad, degradación del suelo y una mayor vulnerabilidad económica para las comunidades productoras.`,
      content1: `Los sistemas agroforestales integran árboles, cultivos agrícolas y, en algunos casos, ganadería, ofreciendo una solución basada en la naturaleza que combina producción y conservación.`,
      subhead1: '¿Qué son los sistemas agroforestales?',
      body1: `Los sistemas agroforestales son modelos productivos que incorporan especies leñosas dentro de parcelas agrícolas, creando interacciones ecológicas beneficiosas.`,
      body2: `Estos sistemas pueden adaptarse a distintas escalas y contextos, desde huertos familiares hasta parcelas comunitarias.`,
      subhead2: 'Beneficios productivos y ambientales',
      body3: `La presencia de árboles mejora la fertilidad del suelo, regula el microclima y protege los cultivos frente a eventos climáticos extremos.`,
      body4: `Además, la diversificación productiva reduce riesgos económicos al generar múltiples fuentes de alimentos e ingresos.`,
      immersiveImg: 'assets/repo/agroforestal-esquema.jpg',
      subhead3: 'Implementación participativa y acompañamiento técnico',
      body5: `Las comunidades aportan conocimientos sobre especies locales y prácticas tradicionales, mientras que los profesionales voluntarios pueden apoyar en el diseño del sistema y su manejo a largo plazo.`,
      conclusion: `Los sistemas agroforestales fortalecen la seguridad alimentaria y promueven territorios productivos más resilientes y equilibrados.`,
    },
    10: {
      category: 'Ciudades y hábitat',
      title: 'Espacios públicos verdes como infraestructura social y ambiental',
      heroImg: 'assets/repo/ciudades1-full.jpg',
      intro: `En muchas ciudades, especialmente en contextos vulnerables, los espacios públicos son escasos, degradados o carecen de condiciones ambientales adecuadas para el encuentro social y el bienestar colectivo.`,
      content1: `Los espacios públicos verdes se consolidan como una solución basada en la naturaleza que cumple una doble función: actuar como infraestructura ambiental para la adaptación climática y como infraestructura social que fortalece la cohesión comunitaria.`,
      subhead1: 'El rol de los espacios verdes urbanos',
      body1: `Los parques, plazas y corredores verdes aportan servicios ecosistémicos clave, como la regulación térmica, la infiltración de agua y la mejora de la calidad del aire.`,
      body2: `Al mismo tiempo, funcionan como lugares de encuentro, recreación y expresión cultural, esenciales para la vida urbana y la salud mental de la población.`,
      subhead2: 'Impactos en la calidad de vida y el clima urbano',
      body3: `La incorporación de vegetación en el espacio público contribuye a reducir las islas de calor y a mitigar los efectos de eventos climáticos extremos, como lluvias intensas.`,
      body4: `Estos beneficios son especialmente relevantes en barrios densos y con déficit histórico de áreas verdes.`,
      immersiveImg: 'assets/repo/espacios-verdes-esquema.jpg',
      subhead3: 'Gestión comunitaria y apoyo profesional',
      body5: `Las comunidades pueden participar activamente en el cuidado y activación de estos espacios, mientras que los profesionales voluntarios pueden apoyar en el diseño paisajístico, la planificación y la gestión sostenible.`,
      conclusion: `Los espacios públicos verdes, cuando se diseñan e implementan de forma participativa, se convierten en infraestructuras clave para ciudades más justas, saludables y resilientes.`,
    },
    11: {
      category: 'Ciudades y hábitat',
      title:
        'Naturación urbana: cubiertas y muros verdes en contextos de bajos recursos',
      heroImg: 'assets/repo/ciudades2-full.jpg',
      intro: `El déficit de áreas verdes y el sobrecalentamiento de las viviendas son problemas comunes en barrios de bajos recursos, donde la infraestructura urbana suele ser limitada.`,
      content1: `La naturación urbana, a través de cubiertas y muros verdes, se presenta como una solución basada en la naturaleza que mejora el confort térmico, la calidad ambiental y el bienestar de las personas.`,
      subhead1: '¿Qué es la naturación urbana?',
      body1: `La naturación urbana consiste en integrar vegetación en superficies construidas, como techos y fachadas, mediante sistemas adaptados a las condiciones locales.`,
      body2: `Estas soluciones pueden diseñarse con técnicas de bajo costo, utilizando especies resistentes y sistemas sencillos de riego y drenaje.`,
      subhead2: 'Beneficios ambientales y habitacionales',
      body3: `Las cubiertas y muros verdes reducen la temperatura interior de las viviendas, mejoran el aislamiento acústico y prolongan la vida útil de las edificaciones.`,
      body4: `Además, contribuyen a la mejora del microclima urbano y al aumento de la biodiversidad a pequeña escala.`,
      immersiveImg: 'assets/repo/naturacion-urbana-esquema.jpg',
      subhead3: 'Implementación comunitaria y acompañamiento técnico',
      body5: `La participación de la comunidad es clave para el mantenimiento y apropiación de estas soluciones, mientras que los profesionales voluntarios pueden asesorar en el diseño, selección de especies y seguridad estructural.`,
      conclusion: `La naturación urbana demuestra que es posible mejorar las condiciones habitacionales y ambientales incluso en contextos de recursos limitados.`,
    },
    12: {
      category: 'Ciudades y hábitat',
      title:
        'Diseño participativo de espacios públicos basados en la naturaleza',
      heroImg: 'assets/repo/ciudades3-full.jpg',
      intro: `El diseño de espacios públicos suele realizarse sin una participación real de las comunidades, lo que puede generar proyectos poco utilizados o desconectados de las necesidades locales.`,
      content1: `El diseño participativo aplicado a soluciones basadas en la naturaleza permite crear espacios públicos más inclusivos, funcionales y sostenibles, fortaleciendo el vínculo entre las personas y su entorno.`,
      subhead1: '¿Qué es el diseño participativo?',
      body1: `El diseño participativo es una metodología que involucra activamente a la comunidad en las distintas etapas del proyecto: diagnóstico, diseño, implementación y evaluación.`,
      body2: `Este enfoque permite integrar conocimientos locales, dinámicas sociales y valores culturales en las soluciones propuestas.`,
      subhead2: 'Integración de la naturaleza en el espacio público',
      body3: `A través del diseño participativo, es posible incorporar elementos naturales como vegetación, agua y sombra de forma coherente con el uso cotidiano del espacio.`,
      body4: `Estas intervenciones mejoran la habitabilidad urbana y refuerzan el sentido de pertenencia comunitaria.`,
      immersiveImg: 'assets/repo/diseno-participativo-esquema.jpg',
      subhead3: 'Trabajo colaborativo entre comunidad y profesionales',
      body5: `Mientras la comunidad define prioridades y usos, los profesionales voluntarios aportan herramientas técnicas para traducir estas ideas en proyectos viables y sostenibles.`,
      conclusion: `El diseño participativo de espacios públicos basados en la naturaleza es clave para construir ciudades más democráticas, resilientes y alineadas con las necesidades reales de sus habitantes.`,
    },
    13: {
      category: 'Cambio climático',
      title:
        'Soluciones basadas en la naturaleza para la adaptación climática comunitaria',
      heroImg: 'assets/repo/clima1-full.jpg',
      intro: `Las comunidades vulnerables se encuentran entre las más afectadas por los impactos del cambio climático, como inundaciones, sequías, olas de calor y deslizamientos, a pesar de ser las que menos contribuyen a sus causas.`,
      content1: `Las soluciones basadas en la naturaleza (SbN) ofrecen estrategias de adaptación climática que trabajan con los ecosistemas locales para reducir riesgos, fortalecer capacidades comunitarias y aumentar la resiliencia territorial.`,
      subhead1: 'Adaptación climática desde lo local',
      body1: `La adaptación climática comunitaria se centra en reducir la vulnerabilidad de las personas frente a eventos extremos mediante acciones que consideran las condiciones ambientales, sociales y culturales del territorio.`,
      body2: `Las SbN permiten responder a estos desafíos aprovechando funciones naturales como la retención de agua, la regulación térmica y la protección del suelo.`,
      subhead2: 'Ejemplos de soluciones basadas en la naturaleza',
      body3: `Entre las estrategias más comunes se encuentran la restauración de riberas, la reforestación, los humedales artificiales y la infraestructura verde para la gestión del agua.`,
      body4: `Estas soluciones reducen el impacto de eventos climáticos extremos al tiempo que generan beneficios ambientales y sociales adicionales.`,
      immersiveImg: 'assets/repo/adaptacion-climatica-esquema.jpg',
      subhead3: 'Rol de la comunidad y apoyo técnico',
      body5: `Las comunidades participan activamente en la identificación de riesgos y en la implementación de soluciones, mientras que los profesionales voluntarios aportan conocimientos técnicos para fortalecer su efectividad.`,
      conclusion: `Las soluciones basadas en la naturaleza se consolidan como herramientas clave para una adaptación climática justa, inclusiva y sostenible a escala comunitaria.`,
    },
    14: {
      category: 'Cambio climático',
      title:
        'Infraestructura verde como herramienta de mitigación del cambio climático',
      heroImg: 'assets/repo/clima2-full.jpg',
      intro: `El cambio climático está estrechamente vinculado a las dinámicas urbanas, donde el consumo energético, la pérdida de vegetación y la impermeabilización del suelo incrementan las emisiones y los efectos del calentamiento global.`,
      content1: `La infraestructura verde se presenta como una solución basada en la naturaleza que contribuye a la mitigación del cambio climático al incorporar vegetación y procesos ecológicos en el entorno urbano.`,
      subhead1: 'Infraestructura verde y mitigación climática',
      body1: `La vegetación urbana cumple un rol clave en la captura y almacenamiento de carbono, ayudando a reducir la concentración de gases de efecto invernadero.`,
      body2: `Además, la infraestructura verde disminuye las islas de calor urbano, reduciendo la demanda energética para refrigeración.`,
      subhead2: 'Beneficios ambientales y urbanos',
      body3: `Árboles urbanos, parques, cubiertas verdes y corredores ecológicos mejoran la calidad del aire y regulan el microclima.`,
      body4: `Estos beneficios son especialmente relevantes en zonas densamente urbanizadas y con escasez de áreas verdes.`,
      immersiveImg: 'assets/repo/infraestructura-verde-clima-esquema.jpg',
      subhead3: 'Implementación en contextos vulnerables',
      body5: `La implementación de infraestructura verde puede adaptarse a diferentes escalas y presupuestos, con la participación activa de comunidades y el acompañamiento de profesionales voluntarios.`,
      conclusion: `La infraestructura verde no solo mitiga el cambio climático, sino que también mejora la habitabilidad urbana y la resiliencia de las ciudades.`,
    },
    15: {
      category: 'Cambio climático',
      title: 'Planificación territorial resiliente frente al cambio climático',
      heroImg: 'assets/repo/clima3-full.jpg',
      intro: `El cambio climático plantea desafíos crecientes para la planificación territorial, afectando tanto a zonas urbanas como rurales mediante eventos extremos cada vez más frecuentes e intensos.`,
      content1: `La planificación territorial resiliente busca anticipar estos impactos e integrar soluciones basadas en la naturaleza como parte estructural del desarrollo del territorio.`,
      subhead1: '¿Qué es la resiliencia territorial?',
      body1: `La resiliencia territorial se refiere a la capacidad de un territorio para adaptarse, resistir y recuperarse frente a impactos climáticos y ambientales.`,
      body2: `Este enfoque reconoce la interdependencia entre sistemas naturales, sociales y económicos.`,
      subhead2: 'Integración de SbN en la planificación',
      body3: `La incorporación de SbN en la planificación permite proteger ecosistemas clave, reducir riesgos naturales y orientar el crecimiento urbano de forma sostenible.`,
      body4: `Ejemplos incluyen la protección de zonas inundables, la conservación de corredores ecológicos y la infraestructura verde a escala territorial.`,
      immersiveImg: 'assets/repo/planificacion-resiliente-esquema.jpg',
      subhead3: 'Articulación entre actores locales',
      body5: `Las comunidades aportan conocimiento del territorio y sus dinámicas, mientras que los profesionales voluntarios apoyan en el análisis técnico y la formulación de estrategias.`,
      conclusion: `Una planificación territorial resiliente es fundamental para enfrentar el cambio climático de manera preventiva, equitativa y sostenible.`,
    },
    16: {
      category: 'Territorio y paisaje',
      title:
        'Paisajes productivos resilientes en territorios rurales vulnerables',
      heroImg: 'assets/repo/territorio1-full.jpg',
      intro: `Los territorios rurales vulnerables enfrentan múltiples presiones relacionadas con el cambio climático, la degradación ambiental y la fragilidad de los sistemas productivos tradicionales.`,
      content1: `El enfoque de paisajes productivos resilientes propone integrar producción agrícola, conservación ambiental y desarrollo comunitario como una estrategia basada en la naturaleza para fortalecer la sostenibilidad territorial.`,
      subhead1: '¿Qué son los paisajes productivos resilientes?',
      body1: `Se trata de territorios gestionados de manera integral, donde las actividades productivas conviven con ecosistemas naturales y prácticas de conservación.`,
      body2: `Este enfoque reconoce el paisaje como una unidad funcional que articula lo ecológico, lo social y lo económico.`,
      subhead2: 'Beneficios ambientales y productivos',
      body3: `Los paisajes productivos resilientes mejoran la fertilidad del suelo, regulan el ciclo del agua y aumentan la biodiversidad.`,
      body4: `Al mismo tiempo, diversifican las fuentes de ingreso y reducen la vulnerabilidad de las comunidades frente a eventos climáticos extremos.`,
      immersiveImg: 'assets/repo/paisaje-productivo-esquema.jpg',
      subhead3: 'Gestión comunitaria del paisaje',
      body5: `Las comunidades rurales aportan conocimientos tradicionales y prácticas locales, mientras que los profesionales voluntarios pueden apoyar en la planificación territorial y el diseño de sistemas productivos sostenibles.`,
      conclusion: `El desarrollo de paisajes productivos resilientes fortalece la autonomía local y promueve territorios rurales más equilibrados y adaptativos.`,
    },
    17: {
      category: 'Territorio y paisaje',
      title: 'Ordenamiento territorial con enfoque ecosistémico',
      heroImg: 'assets/repo/territorio2-full.jpg',
      intro: `El ordenamiento territorial es una herramienta clave para orientar el uso del suelo y el desarrollo de los territorios, especialmente en contextos expuestos a riesgos ambientales.`,
      content1: `Incorporar un enfoque ecosistémico permite considerar los límites y capacidades de los ecosistemas como base para una planificación territorial más sostenible y resiliente.`,
      subhead1: 'Principios del enfoque ecosistémico',
      body1: `Este enfoque reconoce que los ecosistemas proveen servicios fundamentales como agua, alimentos, regulación climática y protección frente a riesgos naturales.`,
      body2: `El ordenamiento territorial con enfoque ecosistémico busca mantener estos servicios mediante una gestión equilibrada del territorio.`,
      subhead2: 'Aplicación en procesos participativos',
      body3: `La participación comunitaria es esencial para identificar áreas de valor ambiental, zonas de riesgo y usos del suelo prioritarios.`,
      body4: `Los profesionales pueden apoyar con análisis técnicos, cartografía y herramientas de planificación.`,
      immersiveImg: 'assets/repo/ordenamiento-ecosistemico-esquema.jpg',
      subhead3: 'Impactos a largo plazo',
      body5: `Este tipo de ordenamiento contribuye a reducir conflictos por el uso del suelo y a fortalecer la resiliencia territorial frente al cambio climático.`,
      conclusion: `El enfoque ecosistémico en el ordenamiento territorial permite construir territorios más seguros, funcionales y ambientalmente sostenibles.`,
    },
    18: {
      category: 'Territorio y paisaje',
      title: 'Restauración del paisaje como estrategia de cohesión territorial',
      heroImg: 'assets/repo/territorio3-full.jpg',
      intro: `La degradación del paisaje afecta no solo a los ecosistemas, sino también a la identidad, la memoria y la cohesión social de las comunidades.`,
      content1: `La restauración del paisaje se plantea como una solución basada en la naturaleza que permite recuperar funciones ecológicas y fortalecer los vínculos entre las personas y su territorio.`,
      subhead1: 'Paisaje, identidad y territorio',
      body1: `El paisaje es el resultado de la interacción entre la naturaleza y las actividades humanas a lo largo del tiempo.`,
      body2: `Su restauración contribuye a reforzar el sentido de pertenencia y la valoración del territorio.`,
      subhead2: 'Beneficios ecológicos y sociales',
      body3: `La restauración del paisaje mejora la conectividad ecológica, la biodiversidad y la regulación de procesos naturales.`,
      body4: `A nivel social, fomenta la participación comunitaria y el trabajo colectivo.`,
      immersiveImg: 'assets/repo/restauracion-paisaje-esquema.jpg',
      subhead3: 'Procesos colaborativos de restauración',
      body5: `Las comunidades lideran los procesos de recuperación del paisaje, mientras que los profesionales voluntarios aportan criterios técnicos y metodológicos.`,
      conclusion: `La restauración del paisaje es una herramienta poderosa para construir cohesión territorial, resiliencia ambiental y desarrollo comunitario sostenible.`,
    },
    19: {
      category: 'Comunidad y gobernanza',
      title:
        'Gobernanza comunitaria en proyectos de soluciones basadas en la naturaleza',
      heroImg: 'assets/repo/comunidad1-full.jpg',
      intro: `La implementación de soluciones basadas en la naturaleza no depende únicamente de criterios técnicos o ambientales, sino también de la forma en que se toman decisiones y se gestionan los proyectos a nivel local.`,
      content1: `La gobernanza comunitaria se presenta como un componente clave para garantizar que los proyectos SbN respondan a las necesidades reales del territorio y sean sostenibles en el tiempo.`,
      subhead1: '¿Qué se entiende por gobernanza comunitaria?',
      body1: `La gobernanza comunitaria implica procesos de toma de decisiones participativos, transparentes y colectivos, donde la comunidad tiene un rol activo en la planificación, ejecución y seguimiento de los proyectos.`,
      body2: `Este enfoque fortalece la apropiación social de las soluciones y reduce la dependencia de actores externos.`,
      subhead2: 'Beneficios para la sostenibilidad de los proyectos',
      body3: `Los proyectos con gobernanza comunitaria tienden a tener mayor continuidad, ya que la comunidad se involucra en su cuidado y mantenimiento.`,
      body4: `Además, se promueve la equidad en la distribución de beneficios y la resolución colaborativa de conflictos.`,
      immersiveImg: 'assets/repo/gobernanza-comunitaria-esquema.jpg',
      subhead3: 'Rol de comunidades y profesionales',
      body5: `Las comunidades lideran los procesos de decisión, mientras que los profesionales voluntarios pueden aportar herramientas metodológicas, facilitación y apoyo técnico.`,
      conclusion: `La gobernanza comunitaria es un pilar fundamental para el éxito de las soluciones basadas en la naturaleza con impacto social y ambiental duradero.`,
    },
    20: {
      category: `Comunidad y gobernanza`,
      title: `Participación ciudadana como base de la sostenibilidad territorial`,
      heroImg: 'assets/repo/comunidad2-full.jpg',
      intro: `La sostenibilidad territorial requiere la implicación activa de quienes habitan y utilizan el territorio en su vida cotidiana.`,
      content1: `La participación ciudadana permite integrar conocimientos locales, fortalecer el tejido social y generar soluciones más ajustadas a las realidades territoriales.`,
      subhead1: `La participación como proceso continuo`,
      body1: `La participación ciudadana va más allá de la consulta puntual e implica procesos continuos de diálogo, co-diseño y evaluación colectiva.`,
      body2: `Este enfoque favorece la corresponsabilidad y el compromiso a largo plazo con los proyectos territoriales.`,
      subhead2: `Impactos sociales y territoriales`,
      body3: `La participación activa fortalece capacidades locales, promueve el aprendizaje colectivo y mejora la cohesión social.`,
      body4: `Asimismo, contribuye a la construcción de territorios más inclusivos, resilientes y adaptativos.`,
      immersiveImg: 'assets/repo/participacion-ciudadana-esquema.jpg',
      subhead3: `Espacios de colaboración`,
      body5: `Los profesionales voluntarios pueden facilitar metodologías participativas, mientras que las comunidades aportan su conocimiento del territorio y sus dinámicas sociales.`,
      conclusion: `La participación ciudadana es una base indispensable para alcanzar una sostenibilidad territorial real y duradera.`,
    },
    21: {
      category: `Comunidad y gobernanza`,
      title: `Redes de colaboración entre comunidades y profesionales voluntarios`,
      heroImg: 'assets/repo/comunidad3-full.jpg',
      intro: `Los desafíos socioambientales actuales requieren enfoques colaborativos que superen el trabajo aislado de comunidades o profesionales.`,
      content1: `Las redes de colaboración entre comunidades y profesionales voluntarios permiten articular conocimientos, recursos y capacidades para potenciar el impacto de las soluciones basadas en la naturaleza.`,
      subhead1: `¿Qué son las redes de colaboración?`,
      body1: `Son espacios de intercambio y cooperación donde diferentes actores comparten experiencias, saberes y herramientas.`,
      body2: `Estas redes facilitan el aprendizaje mutuo y la replicabilidad de buenas prácticas.`,
      subhead2: `Beneficios para proyectos SbN`,
      body3: `Las redes fortalecen la calidad técnica de los proyectos y amplían su alcance territorial.`,
      body4: `También generan vínculos de confianza y apoyo continuo entre comunidades y profesionales.`,
      immersiveImg: 'assets/repo/redes-colaboracion-esquema.jpg',
      subhead3: `Construcción colectiva de soluciones`,
      body5: `Las comunidades definen las problemáticas y prioridades, mientras que los profesionales voluntarios acompañan con asesoría técnica y seguimiento.`,
      conclusion: `Las redes de colaboración son una herramienta estratégica para escalar soluciones basadas en la naturaleza con impacto social y ambiental.`,
    },
    22: {
      category: 'Métodos y herramientas',
      title:
        'Metodologías participativas para el diseño de soluciones basadas en la naturaleza',
      heroImg: 'assets/repo/metodos1-full.jpg',
      intro:
        'El diseño de soluciones basadas en la naturaleza (SbN) en contextos comunitarios requiere enfoques que reconozcan a la población local como agente activo del proceso y no solo como beneficiaria. Las metodologías participativas surgen como una respuesta a esta necesidad, promoviendo procesos de co-creación que integran saberes técnicos y conocimientos locales.',
      content1:
        'Estas metodologías permiten identificar problemas reales del territorio, priorizar acciones y diseñar soluciones adaptadas al contexto social, cultural y ambiental, fortaleciendo el sentido de pertenencia y la sostenibilidad a largo plazo de los proyectos.',
      subhead1: '¿Qué son las metodologías participativas?',
      body1:
        'Las metodologías participativas son conjuntos de herramientas y dinámicas que facilitan la colaboración entre comunidades, técnicos y otros actores durante el proceso de diseño. Incluyen talleres, mapas colectivos, recorridos territoriales, entrevistas y dinámicas de co-diseño.',
      body2:
        'En el marco de las SbN, estas metodologías ayudan a comprender las dinámicas ecológicas locales desde la experiencia cotidiana de quienes habitan el territorio.',
      subhead2: 'Ventajas en proyectos comunitarios',
      body3:
        'La participación activa de la comunidad mejora la aceptación social de las soluciones, reduce conflictos y permite detectar oportunidades que no suelen emerger en procesos de diseño tradicionales.',
      body4:
        'Además, fomenta el aprendizaje colectivo y el empoderamiento, fortaleciendo capacidades locales para la gestión y mantenimiento de las soluciones implementadas.',
      immersiveImg: 'assets/repo/codisenio.jpg',
      subhead3: 'Rol de los profesionales',
      body5:
        'Los profesionales actúan como facilitadores del proceso, aportando criterios técnicos, estructurando la información y traduciendo las ideas colectivas en propuestas viables.',
      conclusion:
        'Cuando se integran metodologías participativas desde las etapas iniciales, las soluciones basadas en la naturaleza se convierten en procesos compartidos que combinan impacto ambiental, cohesión social y sostenibilidad.',
    },

    23: {
      category: 'Métodos y herramientas',
      title:
        'Herramientas digitales para el diagnóstico territorial participativo',
      heroImg: 'assets/repo/metodos2-full.jpg',
      intro:
        'El diagnóstico territorial es una fase clave para comprender las problemáticas, recursos y dinámicas de un territorio. En proyectos SbN, las herramientas digitales pueden complementar los métodos tradicionales, facilitando la participación y el análisis colectivo de la información.',
      content1:
        'El uso de tecnologías accesibles permite recopilar datos, visualizar información y apoyar la toma de decisiones sin requerir infraestructuras complejas o conocimientos técnicos avanzados.',
      subhead1: '¿Qué tipo de herramientas digitales se utilizan?',
      body1:
        'Entre las herramientas más comunes se encuentran mapas colaborativos en línea, encuestas digitales, sistemas de información geográfica simplificados y aplicaciones móviles para el registro de datos territoriales.',
      body2:
        'Estas herramientas permiten integrar información ambiental, social y espacial de manera visual y comprensible para todos los actores involucrados.',
      subhead2: 'Aportes al proceso participativo',
      body3:
        'Las herramientas digitales facilitan la inclusión de distintos perfiles de participantes, permiten documentar el conocimiento local y hacen más transparente el proceso de diagnóstico.',
      body4:
        'Asimismo, contribuyen a generar registros que pueden reutilizarse en fases posteriores del proyecto, como el diseño, la implementación o la evaluación.',
      immersiveImg: 'assets/repo/mapa-digital.jpg',
      subhead3: 'Limitaciones y consideraciones',
      body5:
        'Es fundamental adaptar las herramientas al contexto, considerando el acceso a tecnología, la alfabetización digital y la necesidad de acompañamiento técnico.',
      conclusion:
        'Bien utilizadas, las herramientas digitales se convierten en aliadas para fortalecer diagnósticos territoriales participativos, sin sustituir el valor del contacto directo con el territorio.',
    },

    24: {
      category: 'Métodos y herramientas',
      title:
        'Prototipado y experimentación en proyectos de soluciones basadas en la naturaleza',
      heroImg: 'assets/repo/metodos3-full.jpg',
      intro:
        'El prototipado y la experimentación son estrategias clave para reducir la incertidumbre y adaptar las soluciones basadas en la naturaleza a contextos reales y cambiantes. En lugar de aplicar soluciones cerradas, estos enfoques promueven el aprendizaje continuo.',
      content1:
        'A través de prototipos a pequeña escala, es posible evaluar el funcionamiento de una solución, identificar mejoras y ajustar el diseño antes de su implementación definitiva.',
      subhead1: '¿Qué es el prototipado en SbN?',
      body1:
        'El prototipado consiste en la creación de versiones preliminares de una solución, que pueden ser temporales, reversibles o de bajo costo. En proyectos SbN, esto puede incluir jardines piloto, sistemas de drenaje experimental o infraestructuras verdes de prueba.',
      body2:
        'Estas intervenciones permiten observar el comportamiento del sistema natural y su interacción con la comunidad.',
      subhead2: 'Aprender haciendo',
      body3:
        'La experimentación fomenta una cultura de prueba y error, donde los fallos se entienden como oportunidades de aprendizaje y mejora.',
      body4:
        'Además, involucra activamente a la comunidad en la evaluación y adaptación de las soluciones, fortaleciendo su apropiación.',
      immersiveImg: 'assets/repo/prototipo-sbn.jpg',
      subhead3: 'Escalabilidad y adaptación',
      body5:
        'Una vez validado un prototipo, la solución puede escalarse o adaptarse a otros contextos, ajustándose a nuevas condiciones territoriales.',
      conclusion:
        'El prototipado y la experimentación permiten desarrollar soluciones basadas en la naturaleza más resilientes, flexibles y alineadas con las realidades locales.',
    },
  };

  constructor(private route: ActivatedRoute) {}

  ngOnInit(): void {
    const id = this.route.snapshot.paramMap.get('id');
    if (id) {
      this.article = this.articlesData[id];
    }
  }
}
